name: CI

on:

  # Triggers the workflow on push or pull request events but only for the main branch

  push:

    branches: [ main ]

  pull_request:

    branches: [ main ]



jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "Eiva"

          replace: "Eivaa"

      - name: Pull All Updates

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'there was a conflict'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: errorshivansh

          commit_user_email: shivanshraghuvanshi2005@gmail.com

          commit_author: errorshivansh <shivanshraghuvanshi2005@gmail.com>

