name: okk

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "ForGo10God"

          replace: "Ryoishin"

      - name: Pull All Updates

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'there was a conflict'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: errorshivansh

          commit_user_email: shivanshraghuvanshi2005@gmail.com

          commit_author: errorshivansh <shivanshraghuvanshi2005@gmail.com>

